# NVCC compiler
NVCC_HOME       = /usr/local/cuda
NVCC            = $(NVCC_HOME)/bin/nvcc
NVCC_FLAG	= -m64 -gencode arch=compute_20,code=sm_20 -gencode arch=compute_35,code=sm_35 -lOpenCL -use_fast_math
